# Generated by Django 5.0.2 on 2024-05-29 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("faculty", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="professors",
            field=models.ManyToManyField(blank=True, related_name="teaching_courses", to="user.professor"),
        ),
        migrations.AddField(
            model_name="coursetype",
            name="academic_field",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="faculty.academicfield"),
        ),
        migrations.AddField(
            model_name="coursetype",
            name="course",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course.course"),
        ),
        migrations.AddField(
            model_name="semestercourse",
            name="course",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course.course"),
        ),
        migrations.AddField(
            model_name="semestercourse",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.professor",
            ),
        ),
        migrations.AddField(
            model_name="semestercourse",
            name="semester",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course.semester"),
        ),
        migrations.AddField(
            model_name="classsession",
            name="semester_course",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course.semestercourse"),
        ),
        migrations.AddField(
            model_name="studentcourse",
            name="semester_course",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course.semestercourse"),
        ),
        migrations.AddField(
            model_name="studentcourse",
            name="student",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.student"),
        ),
        migrations.AddField(
            model_name="studentsemester",
            name="semester",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course.semester"),
        ),
        migrations.AddField(
            model_name="studentsemester",
            name="student",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.student"),
        ),
    ]
