# Generated by Django 5.0.2 on 2024-05-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsemester',
            name='semester_count',
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='semester_status',
            field=models.CharField(choices=[('PAS', 'Passed'), ('FAI', 'Failed'), ('WDR', 'Withdrawn'), ('UNK', 'Unknown')], default='UNK', max_length=3),
        ),
    ]
