# Generated by Django 5.0.6 on 2024-06-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsemester",
            name="semester_status",
            field=models.CharField(
                choices=[
                    ("ONG", "Ongoing"),
                    ("PAS", "Passed"),
                    ("FAI", "Failed"),
                    ("WWS", "Withdrawn with Sanavat"),
                    ("WNO", "Withdrawn No Sanavat"),
                    ("UNK", "Unknown"),
                ],
                default="ONG",
                max_length=3,
            ),
        ),
    ]
