# Generated by Django 5.0.2 on 2024-06-16 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_alter_studentsemester_semester_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="professors",
        ),
    ]
