# Generated by Django 5.0.2 on 2024-05-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_studentsemester_semester_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsemester',
            name='semester_status',
            field=models.CharField(choices=[('ONG', 'Ongoing'), ('PAS', 'Passed'), ('FAI', 'Failed'), ('WWS', 'Withdrawn with Sanavat'), ('WNO', 'Withdrawn No Sanavat'), ('UNK', 'Unknown')], default='UNK', max_length=3),
        ),
    ]
