# Generated by Django 5.0.6 on 2024-06-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_remove_course_professors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsemester",
            name="gpa",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
