# Generated by Django 5.0.6 on 2024-06-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faculty", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicfield",
            name="academic_level",
            field=models.CharField(
                choices=[("B", "Bachelor"), ("M", "Master"), ("D", "Doctorate")],
                max_length=10,
            ),
        ),
    ]
